### COMAKE2: PLEASE DO NOT DELETE THE FILE
#<cvspath>,trunk/<branch-name>/-,<localrev>,<tag-name>/-,<cleancmd>,<makecmd>,disbuild/-,DEP-<N>,unstable/-
demo/front_http_server,,???,???,make clean,make
    third-64/thrift,,1075,thrift_0-9-1-400_PD_BL,,,,DEP-1,
    third-64/boost,,1060,boost_1-56-0-100_PD_BL,,,,DEP-1,
    third-64/json-cpp,,1053,json-cpp_0-6-1-400_PD_BL,,,,DEP-1,
    third-64/protobuf,,982,protobuf_2-4-1-1100_PD_BL,,,,DEP-1,
    third-64/gflags,,860,gflags_2-0-0-100_PD_BL,,,,DEP-1,
    third-64/glog,,836,glog_0-3-3-100_PD_BL,,,,DEP-1,
