/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "http_server_constants.h"



const http_serverConstants g_http_server_constants;

http_serverConstants::http_serverConstants() {
}



