// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "HttpServer.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

class HttpServerHandler : virtual public HttpServerIf {
 public:
  HttpServerHandler() {
    // Your initialization goes here
  }

  void add(std::string& _return, const std::string& request_str) {
    // Your implementation goes here
    printf("add\n");
  }

  void sub(std::string& _return, const std::string& request_str) {
    // Your implementation goes here
    printf("sub\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<HttpServerHandler> handler(new HttpServerHandler());
  shared_ptr<TProcessor> processor(new HttpServerProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

