/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef http_server_CONSTANTS_H
#define http_server_CONSTANTS_H

#include "http_server_types.h"



class http_serverConstants {
 public:
  http_serverConstants();

};

extern const http_serverConstants g_http_server_constants;



#endif
